### PR TITLE
setting values to forms and explicit checkbox labels

### PR DESCRIPTION
**Pull request by jonsource**
Hello, I added a simple functionality for the FormBuilder class

1) You can set all the values of the fields at once - which comes in handy when validating a form (to remember users input) and also when populating the form from an Entity

2) I added the possibility of explicitly adding labels to checkboxes. Sometimes you want to show something to the user (i.e. a link to a file, or a fancy description) and use something else as the value in your application.

Best Regards
Jan

### CODE REVIEW

**Comment by jlambe** [comment]
Sounds interesting, can you provide me an example on how you will use this api ?
Also, I think the `$i` variable in the `makeGroupCheckable` method is not used, so I suppose we can remove it.

**Comment by jonsource** [comment]
Hello, 

in the end of my message I paste a code sample where I use this api.

#### Basically I use the Form::setValues in this scenario:

1. I render a view with a form with no data.
2. User inputs data in form, sends it to server
3. In the controller I validate the data and prepare error messages
4. 
 1. If there are errors: I render the same view, this time with pre-set data in the form (so the user doesn't have to enter them again) and with error messages
 repeat from point 2.
 
 2. If there are no errors: I save the data in my DB and render the success view

#### The explicit checkbox labels are used here to render links

I don't want to save long chunks of text (or markup) in my DB, a simple 0 or 1 is enough
But I wan't to use the elegant {{ Form::checkbox('agree2', ... }} syntax

The ```$i``` in ```makeGroupCheckable``` is used on line 327 and 331 as a means to use the ```$attributes['label']``` instead of the default ```$choice```



I hope I explained my usage well, and once more a big thank-you for themosis.

#### Code examples
 
form.scout.php

```php
<?php Form::setValues($data); ?>
<div>
    {{ Form::open(home_url('kemp/prihlaska')) }}
    {{ Form::label('sign_name', 'Name' ) }}{{ Form::text('sign_name') }}{{ $errors["sign_name"] or '' }}<br/>
    {{ Form::label('phone', 'Phone' ) }}{{ Form::text('phone') }}{{ $errors["phone"] or '' }}<br/>
    {{ Form::label('email', 'E-mail' ) }}{{ Form::email('email') }}{{ $errors["email"] or '' }}<br/>
    <div class="boxes">
        {{ Form::checkbox('agree1', 'Terms of application', null, 
            array('label'=>'<a href="route to .pdf">Terms of application</a>')) }}
        {{ $errors["agree1"] or '' }}<br/>
        {{ Form::checkbox('agree2', 'Payment', null,
            array('label'=>'<a href="route to .pdf">Payment options</a>')) }}
        {{ $errors["agree2"] or '' }}<br/>
    </div>
    {{ Form::submit('submit', 'Send application', array('class'=>'btn btn-red btn-lg apart')) }}
    {{ Form::close() }}
</div>

```
        
formController.php

```php
public function index()
{
    $data = Input::all();
    $errors = array();

    
    if($data) {
        
        // validate name
        if(!Validator::single($data["sign_name"], array('alpha','min:2')))
        {
            $errors["sign_name"]="Enter your name";
        }
        
        // validate phone and email ... and checkboxes
        
        ...
        ...
                    
        if(sizeof($errors))
        {
            //wrap validation errors for styling
            foreach($errors as $k => $v)
            {
                $errors[$k]='<span class="error">'.$v.'</span>';
            }
            return View::make('form',array('errors' => $errors, 'data' => $data));
        }

        insert_in_db($data);
        return View::make('form-success',array('data' => $data);
        
    }
    return View::make('form');
}
    
```

**Comment by jlambe** [comment]
This seems very interesting. It looks like the method has the same behavior as the Laravel Form::model() binding method. I won't directly merge your code as I would like to define this API a little bit more.

Perhaps we could improve the Validation and Form classes to work better together. I would like to add error handling for data and an easy way to specify error messages.

Tip: there is also a `Validator::multiple()` method to validate multiple data at once :+1:

**Comment by jonsource** [comment]
The behavior of setValues of course is not something new :-)

I personally prefer the setting of values to a form and custom handling of validation to more complex approaches like binding a form with a model and chaining of validators etc... While binding a form with a model and a validator chain will probably spare you some time when creating a pretty simple form (like username, email, password), it tends to bog down on more complicated stuff. For me - too much is going on under the hood.

My reasons are these:
1) I've never used a frameworks function like Form::printTheForm(), or Form::inputGroup() - I always created a partial view or something like that where I put the fields one at a time with some more markup around for better styling.

2) Our UX designers always come up with new and creative ways of displaying error messages - so in the end it is much easier for me to write the code from scratch than to bend existing ways of displaying error messages or search and learn complicated API options and input field decorators etc.. So in the end what I need is an array telling me which fields are bad and why.

3) In almost every form I made there was at least one field that required a custom validator - which I most often handled with a few simple regex expressions. While most frameworks allow for robust chaining of validators and different error messages for different reasons why a field is not valid, these advanced features are quite cumbersome.

 I really like the simple way Themosis offers for creating forms now. The only thing in my opinion that would be useful for me would be something along this way:

```Form::displayErrors(array(field_id => message));```
then the Form::input would append a ```<div class="validation_error"> message </div>``` after each input tag (if an error is present).

and ```Form::errorBox(array(message1, message2, ...));```
which would output a ```<ul class="validation_error_box"><li> message1 </li><li> message2 </li></ul>``` structure.

best regards

**Pull request closed without merging**
