### PR TITLE
Routing add service providers

### PR DESCRIPTION
**Pull request by dstollie**
- The Application class now acts more the same way as laravel's Application class does. Main reason I created this updated was because themosis wasn't able to use dependency injection inside for the registration of service providers inside the boot/register methods. This fork fixes this. Instead of fixing it my way I looked add laravel and copy/pasted the necessary stuff. 

- The boot method is now only called when the service provider has a boot method

- Renamed the RouteServiceProvider to RoutingServiceProvider because laravel's names this class also like that. Created a RouteServiceProvider for some more "advanced" users to load new routes.

- This pull request also registers the EventServiceProvider separately instead of in the RouteServiceProvider.

- Added the app() method which works the same as Laravel's and refactored the container() method so that is just refers to the app() method.

- refactored the $container property to $app inside the Application class because the property refers to the application instance and not the container instance

### CODE REVIEW

**Comment by jlambe** [comment]
Can you provide me code samples that this fork has changed/enhanced? so I can better understand it.

I don't like the `app()` function term as compared to Laravel, the bootstrap of the main application is not directly handled by the IoC so that's why I've added the `container()` function instead which makes more sense.

Now perhaps, in order to ease Laravel developers who need to work with WordPress, we can add both functions.

**Comment by dstollie** [comment]
The container() function sill exists, if you pass no arguments to this function you just get the application container. This what the previous code also did:

```php
        $themosis = $GLOBALS['themosis'];

        return $themosis->container;
```

In the last commit i've added a function themosis() which returns the main Themosis instance

**Comment by dstollie** [comment]
@jlambe Could we take a look at this PR to merge this one into the develop. I Really think this PR has some additions to the core we'd reallly like to the see

**Comment by jlambe** [comment]
We could check it but I won't merge it now for the major release. It can include on minor one later on. The current routing is quite stable and tested. I fixed yesterday the container instance issue and merge the helper functions (app, container and themosis).
I'm working on a custom plugin and those features are currently working:
- Auto instantiation by defining objects dependencies in the controller construct
- Route namespace for controllers
- Definition of services providers in both plugin and theme
- Route overriding

I'm currently focusing on latest issues, documentation, plugin boilerplate and new website. Your PR is not lost but we have to look at it carefully as from now on the framework must work for both plugins and themes. I'll merge the current master branch on the dev branch this week and you could look at your PR to change it once the dev merge is done.

**Comment by dstollie** [comment]
Cool im curious for the plugin boilerplate. Becaise themosis uses more and more of the laravel components. Developers expect they can use them similarly as they do in laravel. In my search I found that, that is cirrently not really the case. For example: The boot method was just being calles right after the run method. If you look at laravels documentation youll see that thats not the way it was ment to work. Though it currently seems to work. 

This pr fixes these things by removing the Some self implemented code and replacing it with the way the its also being used in laravel. 

I totally agree with you that chaning these core thing might be tricky and thats also the reason why I think thia should really be implemented in a major version.

Cirrently the router as it is now doesnt completely work if you try some cases. For example, of you want a wordpress route for multiple page titles the router broke. In my other pr I tries foxing that by sperarating the type routes. Im cirrently making the pr somewhat more advanced by maing the router clever enougj to decide to create a wordpress router or a normall route.

I hope you can grab some time to checkout these pra with me, again, I think the additions should be in the next major release.

Oh and if I can help you with writing docs... Tell me im willing to help you

Dennis

**Comment by jlambe** [comment]
I'm closing this one as I'm adding a routing service provider on theme with custom namespace.

**Pull request closed without merging**
