### PR TITLE
Fix routes with conditional parameters - fixes #343

### PR DESCRIPTION
**Pull request by dstollie**

### CODE REVIEW

**Comment by jlambe** [comment]
The code had issues because it didn't handled routes that use a Closure. I've updated the master branch in order fix this. @dstollie Can you test the latest master branch on your side?

**Comment by dstollie** [comment]
Looks like its not working anymore. Whenever i define these routes: the singular for a specific post type is never hitted.

```php
	/**
	 * Route for the default singular page
	 */
	Route::get('singular', [[BASIS_REGELING_POST_TYPE, GEMEENTE_SPECIFIEKE_REGELING_POST_TYPE], 'uses' => 'RegelingenController@singular']);

	/**
	 * Route for the default singular page
	 */
	Route::get('singular', 'PageController@singular');
```

**Comment by dstollie** [comment]
Found the issue!

In illuminate version 5.3.* the 

$key and $value order are like this

```php
        $parameters = Arr::first($action, function ($value, $value) {
            return is_string($value) || is_array($value);
        });

```

in 5.3=2.* they are supposed to be like this

```php
        $parameters = Arr::first($action, function ($key, $value) {
            return is_string($value) || is_array($value);
        });

```

**Comment by jlambe** [comment]
We simply need to require version 5.3 and update the composer.json file for this. I'm locally working with 5.3 which is why it's working on my side and I've just seen the requirements are 5.2. I'll update this.

**Comment by jlambe** [comment]
@dstollie Can you test the latest commit and let me know if all goes as expected?

**Pull request merged**
