### PR TITLE
WIP: Add mix helper

### PR DESCRIPTION
**Pull request by KevinBatdorf**
Continuing on from this discussion: https://github.com/themosis/framework/pull/626

I set it up this time to work anywhere from the public area and in the current theme folder by default since I'm assuming that will be the most common usage.

Let me know if you want more tests or have any other suggestions / ideas

### CODE REVIEW

**Comment by jlambe** [comment]
@KevinBatdorf Sounds good for me. I'm curious to test this one :) Thanks a lot!

**Comment by KevinBatdorf** [comment]
@jlambe ah actually I added a WIP to the title as I wanted to refactor it a bit. It should still work but I was thinking to extract `$publicDir = rtrim(THEMOSIS_PUBLIC_DIR, '/\\')` into a `public_path()` helper similar to how laravel has. I've just been busy the past few days but I'll try to get to it later today or tomorrow.

**Comment by jlambe** [comment]
Ok great!

**Comment by jlambe** [comment]
@KevinBatdorf Looking at the following line:
https://github.com/themosis/framework/blob/master/src/Core/Mix.php#L26

We should remove the call to the `wp_get_theme` function because depending on the context where `mix` is called, the function might not yet exists...

Also, perhaps it is best to store the mix manifest outside the theme directory and put it at application root `bootstrap/cache` directory or does it need to be public ?

**Pull request merged**
