### PR TITLE
Document Facades

### PR DESCRIPTION
**Pull request by Jaspervv**
Document Facades using @method PHPDoc.
This allows for autocomplete even though they're Facades.

Laravel does this themselves as well.

### CODE REVIEW

**Comment by jlambe** [comment]
@Jaspervv This one is a great proposal. I knew about those PHPDoc but never had the time to dig into it. Many thanks for bringing this 👏  By curiosity, is it an automated process ?

**Comment by Jaspervv** [comment]
There might be an automated solution out there, but I did it by hand. 😋

I know there's [Laravel IDE helper][1] which generates a `ide-helper.php` file containing empty functions in the root of your project, which PHPStorm will index.  
I've tried this package once, but decided not to use it because (from what I remember) it generates these functions for everything, causing PHPStorm errors like: `Multiple definitions exist for class Schema`.  
Also this would only really be a solution for when you're working on the project yourself, since you wouldn't put the `ide-helper.php` in your version control.

[1]:https://github.com/barryvdh/laravel-ide-helper

**Comment by Jaspervv** [comment]
Also I didn't do the `Twig` facade. Simply because it has a shit ton of methods, contains [outdated classes][1], and I don't make use of it myself.


[1]:https://github.com/themosis/framework/issues/709

**Comment by jlambe** [comment]
Thanks, coming on next minor release ;)

**Pull request merged**
