### PR TITLE
Refactor the router so that it uses the latest router of laravel itself

### PR DESCRIPTION
**Pull request by dstollie**
So I think I finished the migration the laravel's core router. Though I have to write some unit tests I thought it would be a good idea to just setup this fork so every can test this out.

To get this working:

**1. Checkout this fork:**
```
composer.json

"repositories": [
    {
      "type": "git",
      "url": "https://github.com/dstollie/framework.git"
    }
],
"require": [
    "themosis/framework": "dev-feature/refactor_router_5",
]

$ composer update

```
You can also checkout     "themosis/framework": "dev-feature/refactor_router" to get the router of laravel 4

**2. Update your themes bootstrap.php by simply moving the inclusion of the routes.php outside the themosis_start_app() function**

This is needed because WordPress does not know the non-WordPress routes registered in the routes.php. When WordPress sees an route it tries to find a page by it changes the url so it fits the found page. 

For example: you created a page with the title "welcome". When you visit the page /admin/welcome WordPress automatically changes this url toe /welcome if you've picked "postname" as your permalink structure. To avoid this functionality themosis automatically creates a rewrite_rule using the regex of the route whenever the route gets created see the [createRewriteRule method](https://github.com/dstollie/framework/blob/feature/refactor_router_5/src/Themosis/Route/Route.php#L233).

If you don't replace move inclusion of the routes.php outside the themosis_start_app() function. The rewrite rules will be registered to late and will have no effect.

_Replace this:_

```
/*----------------------------------------------------*/
// Handle application requests/responses.
/*----------------------------------------------------*/
function themosis_start_app()
{
    /*----------------------------------------------------*/
    // Application routes.
    /*----------------------------------------------------*/
    require themosis_path('theme') . 'routes.php';

    do_action('themosis_parse_query', $arg = '');

    /*----------------------------------------------------*/
    // Run application and return a response.
    /*----------------------------------------------------*/
    do_action('themosis_run');
}
```

_With this:_

``` php
themes/mytheme/bootstrap/bootstrap.php

/*----------------------------------------------------*/
// Application routes.
/*----------------------------------------------------*/
require themosis_path('theme') . 'routes.php';

/*----------------------------------------------------*/
// Handle application requests/responses.
/*----------------------------------------------------*/
function themosis_start_app()
{
    do_action('themosis_parse_query', $arg = '');

    /*----------------------------------------------------*/
    // Run application and return a response.
    /*----------------------------------------------------*/
    do_action('themosis_run');
}
```

**3. DONE. Now you can just use the functionality of Laravel's router**

Here is some example code of what you can do:

``` php
routes.php

Route::middleware('authenticated', Starter\Middleware\AuthenticatedMiddleware::class);

Route::middlewareGroup('admin', ['authenticated']);


Route::group(['middleware' => 'admin'], function () {
	/**
	 * Route for the default page
	 */
	Route::get('front', 'PageController@front');
});

Route::group(['middleware' => 'admin', 'prefix' => 'admin'], function () {

	/**
	 * Route for the default page
	 */
	Route::get('test/test', function ($name = 'none') {
		return 'welcome ' . $name;
	});

	Route::get('test/{name?}', function ($name = 'none') {
		return 'welcome ' . $name;
	});
});
```

To get this working you have register the middleware class and load load the namespace using psr4.

I did this by going to the composer file and autoload a special middleware folder:

```
composer.json

"psr-4": {
    "Starter\\Middleware\\": "htdocs/content/themes/starter/resources/middleware"
}
```

And lastly creating the middleware itself.

``` php
themes/mytheme/resources/middleware/AuthenticatedMiddleware.php

namespace Starter\Middleware;

use Closure;

class AuthenticatedMiddleware
{
	public function handle($request, Closure $next) {

		if(!is_user_logged_in()) {
			return 'log eerst in';
		}

		return $next($request);
	}
}
```

Looking forward to test this further with you. I really think this is a next step for Themosis to become a really big player in the WordPress community.

Greetz,

Dennis

### CODE REVIEW

**Comment by jlambe** [comment]
So I ran first tests and basically it's working :+1: 
But there is an issue with the HTTP headers.

I've run the following route test:
```php
Route::get('test/{name?}', function($name = 'none')
{
	return View::make('pages.test')->with('name', $name);
});
```
When navigating in the browser to this url: `http://domain.tld/test/julien`, it renders correctly into the browser but the header response status is `404` because the URI is not recognized by WordPress.

http_status

I think we need to check the core code and find a way to make it understand to WordPress.

Also, I'm not sure we can keep the default Themosis routes like `front`, `page`, ... as these are template functions, I think we should create a middleware to handle this, no? I don't have experience with Laravel 5 features yet so any advice or suggestions is very welcomed :wink:

**Comment by jlambe** [comment]
Also, I haven't yet tested but in core, the templates functions are used right after the `template_redirect` action hook. I'll test it but I think it's best to include the `routes.php` file during this action in fact in place of in the middle of the theme's `functions.php` file (start.php).

**Comment by dstollie** [comment]
@jlambe I think this is due the rewrite rules not being flushed. can you flush them by going to the permalink setings page and resbumit that page. It should be fixed after that

**Comment by jlambe** [comment]
Will test your changes. Indeed it works with flushing rewrite rules.
Also I've noticed that if a WordPress route is defined before a regular one, the regular one was accessible but weirdly the response returned is the one from the WordPress route. But perhaps your change is fixing this.
Also, what I was think is to delete the WordPress routes and in place detect if the current route is a WordPress one, pass it the main `WP_Post` and `WP_Query` variables so we can run the famous WordPress Loop.

```php
Route::get('/', function($post, $query)
{
    // WordPress route...$post and $query are available...
    // I suspect WordPress to automatically send them but we need to be sure...
});

// in place of...
Route::get('home', function(){});
```

**Comment by dstollie** [comment]
The order of checking routes will be: non-wordpress routes. wordpress routes. Non WordPress routes are more specific and should be loaded first in my opinion.

I dont think that removing the conditional tags would be a good solution and would break the way how WordPress works. A WordPress developer thinks in archives,singulars,templates etc.. removing a way to make specific pages for these different kind of pages would make alot of things harder. 

We could make an addition to the router to be able to autoload the WP_Post and the WP_Query instance using automatic resolution of the ioc container. LIke this: https://laravel.com/docs/4.2/ioc#automatic-resolution

I think we should go to a point to put this pr asap in the new version of Themosis and smoothly going to a point where Themosis uses most of laravel's packages instead of its own implementation

**Comment by jlambe** [comment]
Let's dive into this automatic resolution stuff in order to provide WP_Post and the WP_Query.
Ok to give non-wordpress routes precedence over WordPress ones.

This PR feature should be included with next major version 1.3.0 where core illuminate packages will be included as well.

**Comment by jlambe** [comment]
Merged and need more feedback / tests.

**Pull request closed without merging**
