### PR TITLE
Fix almost all PHPStan Level 0 errors

### PR DESCRIPTION
**Pull request by szepeviktor**
Was #681 

@jlambe These are the X-Files I am not able to resolve :( Could you fix them?

```
 ------ ---------------------------------------------------------------------------------
  Line   Core/Providers/CoreServiceProvider.php
 ------ ---------------------------------------------------------------------------------
  37     Call to an undefined method Themosis\Core\Providers\CoreServiceProvider::all().
 ------ ---------------------------------------------------------------------------------
missing method?

 ------ ------------------------------------------------------------------------------------------------------------
  Line   Field/Factory.php
 ------ ------------------------------------------------------------------------------------------------------------
  135    Return typehint of method Themosis\Field\Factory::date() has invalid type Themosis\Field\Fields\DateField.
  143    Call to an undefined method Themosis\Field\Factory::make().
 ------ ------------------------------------------------------------------------------------------------------------
removed DateField?
make() missing from FieldFactoryInterface?

 ------ -----------------------------------------------------
  Line   Forms/Contracts/FormFactoryInterface.php
 ------ -----------------------------------------------------
  18     Class Themosis\Field\Fields\FieldBuilder not found.
 ------ -----------------------------------------------------
FieldBuilder missing?

 ------ ------------------------------------------------------------------------------
  Line   Metabox/Controllers/MetaboxApiController.php
 ------ ------------------------------------------------------------------------------
         Class App\Http\Controllers\Controller not found and could not be autoloaded.
 ------ ------------------------------------------------------------------------------
in #681
```

### CODE REVIEW

**Comment by jlambe** [comment]
Hi @szepeviktor, before merging this. Can you provide me explanation about your package `szepeviktor/phpstan-wordpress` ?

I haven't yet dig into static analysis but why adding a dependency on one of your package, what does it fix in addition to the default php-stan one ?

Because of the `WordPress` label use in your package name, I'm wondering what it does? Scaning WordPress files ? If so why bother as WordPress is a dependency and we're not looking to fix it.

Thanks for providing additionnal information.

**Comment by szepeviktor** [comment]
> why adding a dependency on one of your package, what does it fix in addition to the default php-stan one ?

Hi @jlambe 

1. it grabs `giacocorsiglia/wordpress-stubs` so phpstan can analyze **calls** WordPress core functions
1. it handles a handful of very special cases when plain phpstan would report false positives https://github.com/szepeviktor/phpstan-wordpress/tree/master/src

Not much!

**Comment by szepeviktor** [comment]
> why bother as WordPress is a dependency

WordPress core is a mix of clean code + side-effects, so we need the stubs to prevent actual execution of side-effect.

**Comment by jlambe** [comment]
@szepeviktor Once merged, how can we run a static analysis ? Perhaps we can add a script to the `composer.json` file to run the analysis ?

**Comment by szepeviktor** [comment]
@jlambe Yes: https://github.com/themosis/framework/pull/742

**Comment by jlambe** [comment]
@szepeviktor The PR is finally merged. If I'm not wrong, current configuration is set on Level 2 which sadly found 88 errors 😭 

Perhaps we could later set the level to `0` and fix "entry" level issues and gradually increase the level, what do you think ?

**Comment by szepeviktor** [comment]
Yes, gradually.

0 is not really is Level, it is a sanity check.

2 is for poorly written code, 4 is for general use, `max` is for robust code.

**Comment by jlambe** [comment]
😆 ok, well let's keep it this way then and let's start slowly fixing those 88 code errors. Thanks!

**Comment by szepeviktor** [comment]
@jlambe Please note that my phpstan extension is rapidly improving, it is now at `v0.3.0`

**Comment by jlambe** [comment]
I saw, I've already set the minimum version to `0.3` 😉

**Pull request merged**
