### PR TITLE
Admin pageslug fix

### PR DESCRIPTION
**Pull request by besrabasant**
Fix resolving of WP admin page parent hook name.

### CODE REVIEW

**Comment by jlambe** [comment]
@besrabasant Thanks for this PR. Could you bring some context about your issue ? What does it fix exactly ?

**Comment by besrabasant** [comment]
Thanks @jlambe 

When you create a parent page and use special characters such as **&** in the title and create **Page routes** other than `/`, then the routes cannot render the correct view.

For example
```
$page = Page::make('drinks-wines', 'Drinks & Wines')
    ->set();

$page->route('/some-more-wine', function () {
    return view('some-more-wine');
});
```

This PR fixes this issue. Also now you can add **subpages** to the **Pages** menu.

**Comment by jlambe** [comment]
@besrabasant Ok thanks for the explanation.

**Comment by jlambe** [comment]
@besrabasant I've just test your example with current version of the framework and everything is working as expected. I can't reproduce your issue.

Also, note that based on your example, the route defined as `/some-more-wine` is only accessible at this URL `http://domain.test/cms/wp-admin/admin.php?page=drinks-wines&action=%F2some-more-wine`

> You should omit the left slash as in fact, the route parameter is the `action` query parameter value, not a URI.

In your example, it is best to set `some-more-wine` as a value and then you can access the page at this URL `http://domain.test/cms/wp-admin/admin.php?page=drinks-wines&action=some-more-wine`.

Can you provide a code sample that reproduce your issue exactly ?

**Pull request closed without merging**
