### PR TITLE
improved radio widget

### PR DESCRIPTION
**Pull request by cdarken**
Better handling of input of type radio and checkbox values from non numeric options array keys.

### CODE REVIEW

**Comment by cdarken** [comment]
Did you take a look at this?

**Comment by jlambe** [comment]
Not yet but I will for the release 1.2.0. Now I've planned to probably fork the Laravel Form classes and replace entirely the current api.

**Comment by cdarken** [comment]
That seems like a good idea. Though your multiple checkbox and radio methods are pretty useful. The one functionality that is needed is form macros to be able to extend it.

**Comment by jlambe** [comment]
:+1:

**Comment by cdarken** [comment]
Ok, here are the examples for the 2 improvements related to radio widgets:

1. non numeric keys
In the current implementation, the radios are using for values only the value on the array given as argument
For instance:
```
Form::radio('gender', array(
    'woman',
    'man'
))
```
will render as:
```
<label><input type="radio" value="woman" name="gender[]">Woman</label>
<label><input type="radio" value="man" name="gender[]">Man</label>
```

With my change it will be possible to use this:
```
Form::radio('gender', array(
    '1' => 'A woman',
    '2' => 'A man'
))
```
that will render to this:
```
<label><input type="radio" value="1" name="gender">A woman</label>
<label><input type="radio" value="2" name="gender">A man</label>
```

2. the other improvement is that in the case of radios the [] notation is not needed, as we always can select only one value. You can observe the difference in the above examples.

**Pull request closed without merging**
