### PR TITLE
Filter

### PR DESCRIPTION
**Pull request by mwerezi**
added Filter facade which is basically a copy of what's in Action.

We could have a common IHook interface in future as they both have same API.

I didn't do the filter version of:

- Action
- ActionNotifier
- ActionObserver
- ActionSubject

Not sure why they are needed.

### CODE REVIEW

**Comment by jlambe** [comment]
That's great! Action, ActionNotifier/Observer/Subject are used internally but should be deprecated in future releases.
Can you add unit tests for this as well before merging?

**Comment by mwerezi** [comment]
Will do

#271

**Comment by jlambe** [comment]
:+1:

**Comment by mwerezi** [comment]
@jlambe Couldn't do any tests i'm afraid as I ran into lots of problems, mainly:

- Can't use the facade as they are loaded in the after_setup_theme hook
- Tried using the FilterBuilder directly and inject a new Container object. However i got an error as the helpers.php file is not included in the bootstrap and FilterBuilder uses str_contains so thats undefined.

I think we'll need to wait until we can do better DI and testing

**Comment by jlambe** [comment]
Hmm weird your facades are loaded in the `after_setup_theme` hook, only class aliases are currently defined in this hook so they're available on both plugin and theme.
Anyway I'll take a look to properly setup unit tests, I need to fix this before adding more features.

**Comment by mwerezi** [comment]
thanks

Maybe i was doing it totally the wrong way.

**Comment by mwerezi** [comment]
just wondering, are you planning to merge this after new unit tests are set up?

**Comment by jlambe** [comment]
Yes I'll merge it probably for next release.

**Comment by jlambe** [comment]
Merged and fixed. You now have Action and Filter classes. Available from the container like so as well:
```php
$container = container();

$container['action']->add('init', function(){});
$container['filter']->add('esc_attr', function(){});
```

**Pull request closed without merging**
