### PR TITLE
Refactor mix helper

### PR DESCRIPTION
**Pull request by KevinBatdorf**
I refactored this to model Laravel much more closely. I also added a check for the wp function to make sure it exists before being used (and I removed others). It should exist at the point when it's needed anyway.

One thing though, I think the webpack.mix.js file in the default theme should look like this:

```
mix.setPublicPath('dist')

mix.js('assets/js/theme.js', 'dist/js/theme.min.js')
    .sass('assets/sass/style.scss', 'dist/css/theme.css')
    .sass('assets/sass/woocommerce.scss', 'dist/css');

if (mix.inProduction()) {
	mix.version();
}
```

Laravel compiles assets to the `public` dir and themosis goes to `htdocs/dist` with the important part being the addition of the `/dist`. 

This cleans up the asset builder and lets the code look like this:
```
Asset::add('theme_styles', mix('css/theme.css'), [], $theme->getHeader('version'))
    ->setType('css')->to('front');
```

with the manifest file like this:
```
{
    "/js/theme.min.js": "/js/theme.min.js?id=bf37ccc8bbe248fe79e1",
    "/css/theme.css": "/css/theme.css?id=ba9aead02aea5cc7befb",
    "/css/woocommerce.css": "/css/woocommerce.css?id=edc42852683a037481e7"
}
```

Question: mix in production mode will only add the cache buster id when changes have been made to the relevant files. It might be a nice feature to have the asset handler notice there is an `id` parameter in the file name, then use that as the version instead. Thoughts?

That way instead of `theme.css?id=ba9aead02aea5cc7befb&ver=1.0.0` 
you get `theme.css?ver=ba9aead02aea5cc7befb`

### CODE REVIEW

**Comment by jlambe** [comment]
I have to test this feature fully first before making it as the default. One question though, if a developer is compiling theme assets and also application assets from the root, each asset is loaded at different URLs. Where is the manifest loaded for all application assets ? Will it still be at the theme location for root assets ?

**Comment by KevinBatdorf** [comment]
If you have mix installed at root you would have to point the mix public path in that webpack.mix.js file to somewhere public like `mix.setPublicPath('htdocs/dist')` then when you want to use the `mix()` helper anywhere else you just pass in a second parameter relative to the web root ("htdocs/") to find the manifest path, like `mix('css/theme.css', 'dist')`. 

The default second parameter is the theme's dist folder (which makes sense as the average user would be working from there), but you can override it as mentioned above.

Check out the MixTest.php file updated here for some examples

**Comment by jlambe** [comment]
I didn't know for the second parameter. Ok sounds like everything is covered for me now, let's merge this. Thank you!

**Comment by KevinBatdorf** [comment]
@jlambe Thanks. What do you think about the question I proposed above regarding WP's version parameter?

**Comment by jlambe** [comment]
The idea is to replaced the `ver` parameter value appended by WordPress with the `id` of Mix. But can we control on the `id` parameter and can we remove it?

Also, I'm wondering how developers might react about no longer define a version number on their own assets ? Perhaps we can open an issue on this and discuss it for a `2.1` release as it is now time to release 2.0 stable.

**Comment by KevinBatdorf** [comment]
Well, the idea is that mix will control the versioning based on _actual_ changes to the assets, where the built-in WP mechanism  relies on the developer to pass in the parameter manually (via a $ver param). 

The `id` from mix is only appended if you set `mix.version();` in the mix.manifest.js file so it's optional, but the idea is automation, so you don't have to update the $ver param every time you make a change and need to bust the browser cache.

Maybe use this feature only if the developer does not pass anything to the $ver param?

I'll open an issue.

**Comment by jlambe** [comment]
I recently saw that some core developers of WordPress also use the `filemtime` PHP function as the version number. This always set the `ver` value with the last modified time, so people don't have to update it manually.

Adding some conditions if the version number is missing could be a potential idea.

**Comment by KevinBatdorf** [comment]
I don't think that will work with mix as it looks like it touches the file each time you run it it (I'm in Thailand and it's 15:24 here now).
Screen Shot 2019-03-22 at 3 25 02 PM

Mix will only update the `id` if they detect the file was changed

**Comment by jlambe** [comment]
I'm currently testing mix on the theme but it seems to not work on my setup.

Calling `mix(css/theme.css)` to specify the asset path, returns the following path:

```php
css/theme.css?id=395b1128a14668f0bb87
```

which WordPress can't find as it doesn't abstract the query variable from the path. Have you been able to set this up on your installation ?

**Comment by KevinBatdorf** [comment]
@jlambe Well, I thought it was working, but now I'm also seeing an error. Not sure if I changed something or maybe tested properly with versioning.

So I guess for this to work with `mix.version();` it would _require_ that `id` param to be handled behind the scenes.

**Comment by KevinBatdorf** [comment]
Does everything work without the addition of `mix.version()` ?

**Comment by jlambe** [comment]
Yes it does work without setting `mix.version()`.

The issue is with the framework asset finder. Because the relative path defined is used to locate the file on the system. We should update the finder class to handle query parameters to define the file path.

I think I'm going to postpone this feature for later release `2.1` so we can be sure to test it properly.

**Comment by KevinBatdorf** [comment]
Actually, I definitely had this working, but I believe in the pre-refactor. It might have been that the file was called more directly? I remember seeing the query var like this in the dev tools so it had to have been called correctly:

`theme.css?id=ba9aead02aea5cc7befb&ver=1.0.0` 

Anyway, we could just strip the params though like this (in Asset/Finder.php) as it should not be needed regardless. I'll open an issue now

`$path = trim(strtok($path, '?'), '\/');`

**Comment by jlambe** [comment]
@KevinBatdorf I've already opened an issue #636 ;)

**Pull request merged**
